### PR TITLE
Migration to metrics from stats package

### PR DESCRIPTION
**Pull request by olegbespalov**
# What?

* Migration to `metrics` from `stats`
* README fixes

# Why?

`stats` will be removed soon

### CODE REVIEW

**Comment by amelkikh** [comment]
up

**Comment by fabricelaborie** [comment]
can someone guide me on how to build xk6-dashboard  to include this pull request ? as the xk6 build --with github.com/szkiba/xk6-dashboard@latest fails as  the pull request is not merged yet ?

**Comment by olegbespalov** [comment]
Hi @fabricelaborie ,

Something like, should help:
```
xk6 build --with github.com/szkiba/xk6-dashboard=github.com/olegbespalov/xk6-dashboard@ce90ed0
```

**Comment by 0x3c** [comment]
@szkiba Could you please merge this PR?

**Comment by szkiba** [comment]
@olegbespalov  thank you for your contributions!

**Pull request merged**
